endpointUri: ""

httpVerb: "GET"

outputTopic: "api-poller-source-output"

pollInterval: 5000

brokers: "localhost:9092"

# Customize 'dataflow' label
dataflowName: "my-dataflow"

# Customize 'instance' label
instanceName: "api-poller-source"

# Customize 'customer' label
customerName: "global"
